include: package:extra_pedantic/analysis_options.yaml

linter:
  rules:
    prefer_single_quotes: true
    prefer_final_parameters: false
    sort_pub_dependencies: false
    prefer_expression_function_bodies: true

analyzer:
  exclude:
    - "**/*_model.g.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target:  ignore

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options